/**
 * The themes the picker offers.
 *
 * Only names and copy live here — every colour and radius is in themes.css,
 * generated by scripts/build-themes.mjs. Nothing duplicates a palette, so the
 * swatches, the app and the mockups cannot drift apart.
 */
export const THEMES = [
  { id: 'default', label: 'Default', blurb: 'What you have now' },
  { id: 'ink', label: 'Ink', blurb: 'Warm paper, tight corners' },
  { id: 'void', label: 'Void', blurb: 'No outlines, true black' },
  { id: 'neon', label: 'Neon', blurb: 'Sharp and high contrast' },
  { id: 'bloom', label: 'Bloom', blurb: 'Soft, round, low contrast' },
];

export const THEME_MODES = [
  { id: 'system', label: 'System' },
  { id: 'light', label: 'Light' },
  { id: 'dark', label: 'Dark' },
];

const THEME_IDS = THEMES.map((t) => t.id);
const MODE_IDS = THEME_MODES.map((m) => m.id);

export function isTheme(value) {
  return THEME_IDS.includes(value);
}

export function isThemeMode(value) {
  return MODE_IDS.includes(value);
}

/** Storage key shared by the pre-paint script and the picker. */
export const THEME_STORAGE_KEY = 'traco.theme.v1';
