import { writeFileSync } from 'node:fs';

/**
 * Generates app/themes.css from one palette table.
 *
 * The palettes live here rather than in the stylesheet so the picker's swatches
 * and the app's own variables can never drift apart — both come out of this
 * file. Re-run with `node scripts/build-themes.mjs` after any edit.
 *
 * A theme is not a hue swap: each one carries its own radius, whether cards are
 * outlined, and whether anything casts a shadow. That is why --radius,
 * --card-border and --card-shadow are tokens alongside the colours.
 */

export const THEMES = {
  default: {
    label: 'Default',
    blurb: 'What you have now',
    radius: '1rem',
    control: '0.625rem',
    outlined: true,
    shadow: { light: 'none', dark: 'none' },
    light: {
      bg: '#f6f7f9', surface: '#ffffff', 'surface-2': '#f1f3f6', border: '#e2e5ea',
      text: '#12161c', muted: '#646d7a', brand: '#4f46e5', 'brand-text': '#ffffff',
      good: '#059669', warn: '#b45309', over: '#dc2626', track: '#e6e9ee',
    },
    dark: {
      bg: '#0b0e13', surface: '#141922', 'surface-2': '#1b212c', border: '#262e3b',
      text: '#e8ecf2', muted: '#8d97a6', brand: '#6366f1', 'brand-text': '#ffffff',
      good: '#34d399', warn: '#fbbf24', over: '#f87171', track: '#232b38',
    },
  },

  ink: {
    label: 'Ink',
    blurb: 'Warm paper, tight corners',
    radius: '0.5rem',
    control: '0.375rem',
    outlined: true,
    shadow: { light: 'none', dark: 'none' },
    light: {
      bg: '#f4efe4', surface: '#fbf7ee', 'surface-2': '#ece5d6', border: '#d9cdb6',
      text: '#2a2118', muted: '#7a6a55', brand: '#1f3a5f', 'brand-text': '#fbf7ee',
      good: '#3f6212', warn: '#92400e', over: '#9f1239', track: '#e3dac8',
    },
    dark: {
      bg: '#16120c', surface: '#1e1913', 'surface-2': '#26201a', border: '#3a3126',
      text: '#f0e7d8', muted: '#a2917a', brand: '#9ab8dd', 'brand-text': '#16120c',
      good: '#a3d14b', warn: '#f0b429', over: '#f2777a', track: '#2e2820',
    },
  },

  void: {
    label: 'Void',
    blurb: 'No outlines, true black',
    radius: '1.25rem',
    control: '0.875rem',
    outlined: false,
    shadow: { light: '0 1px 3px rgba(15, 15, 20, 0.07)', dark: 'none' },
    light: {
      bg: '#ffffff', surface: '#f7f7f8', 'surface-2': '#efeff1', border: 'transparent',
      text: '#000000', muted: '#6e6e73', brand: '#6d28d9', 'brand-text': '#ffffff',
      good: '#047857', warn: '#b45309', over: '#dc2626', track: '#e6e6e9',
    },
    dark: {
      bg: '#000000', surface: '#0c0c10', 'surface-2': '#16161c', border: 'transparent',
      text: '#ffffff', muted: '#8a8a96', brand: '#a78bfa', 'brand-text': '#14001f',
      good: '#3ddc84', warn: '#ffd166', over: '#ff5d5d', track: '#1c1c24',
    },
  },

  neon: {
    label: 'Neon',
    blurb: 'Sharp and high contrast',
    radius: '0.25rem',
    control: '0.25rem',
    outlined: true,
    shadow: { light: 'none', dark: 'none' },
    light: {
      bg: '#f2f4f5', surface: '#ffffff', 'surface-2': '#e8ecee', border: '#cbd5d8',
      text: '#06131a', muted: '#5a6b73', brand: '#0891b2', 'brand-text': '#ffffff',
      good: '#047857', warn: '#a16207', over: '#be123c', track: '#dbe3e6',
    },
    dark: {
      bg: '#08080c', surface: '#101018', 'surface-2': '#16161f', border: '#2b2b3a',
      text: '#f0f0ff', muted: '#7d7d96', brand: '#22d3ee', 'brand-text': '#04141a',
      good: '#22e06a', warn: '#ffcc00', over: '#ff2e63', track: '#1c1c28',
    },
  },

  bloom: {
    label: 'Bloom',
    blurb: 'Soft, round, low contrast',
    radius: '1.5rem',
    control: '1rem',
    outlined: false,
    shadow: { light: '0 2px 14px rgba(88, 68, 160, 0.09)', dark: 'none' },
    light: {
      bg: '#f3f0f9', surface: '#ffffff', 'surface-2': '#eeeaf7', border: 'transparent',
      text: '#2e2a3d', muted: '#7a7490', brand: '#7c5cff', 'brand-text': '#ffffff',
      good: '#2f9e6e', warn: '#c4881f', over: '#e0576b', track: '#e6e0f4',
    },
    dark: {
      bg: '#171426', surface: '#211d33', 'surface-2': '#2a2540', border: 'transparent',
      text: '#ece9f7', muted: '#9c95b8', brand: '#b39dff', 'brand-text': '#1a1030',
      good: '#5fd9a3', warn: '#ffd166', over: '#ff8fa3', track: '#322c4a',
    },
  },
};

function vars(theme, mode, indent = '  ') {
  const c = theme[mode];
  const lines = Object.entries(c).map(([k, v]) => `${indent}--${k}: ${v};`);
  lines.push(`${indent}--radius: ${theme.radius};`);
  lines.push(`${indent}--radius-control: ${theme.control};`);
  lines.push(
    `${indent}--card-border: ${theme.outlined ? '1px solid var(--border)' : '1px solid transparent'};`,
  );
  lines.push(`${indent}--card-shadow: ${theme.shadow[mode]};`);
  return lines.join('\n');
}

const out = [];
out.push('/*');
out.push(' * GENERATED by scripts/build-themes.mjs — do not edit by hand.');
out.push(' *');
out.push(' * Three blocks per theme, and the order matters:');
out.push(' *   1. the light palette, unconditionally');
out.push(' *   2. the dark palette when the OS says dark AND the user has not forced light');
out.push(' *   3. the dark palette when the user has forced dark, whatever the OS says');
out.push(' *');
out.push(' * That is what makes "System" mean system while still letting someone pin a');
out.push(' * mode. data-theme / data-mode are set on <html> before first paint.');
out.push(' */');
out.push('');

for (const [key, theme] of Object.entries(THEMES)) {
  // The default theme also answers when no theme is set at all — a signed-out
  // page, or an account that has never chosen. That fallback is written as
  // :root:not([data-theme]) rather than a bare :root on purpose: a bare :root
  // matches under EVERY theme and is only beaten on specificity, so the default
  // palette would silently underlie all the others and one careless selector
  // later would let it through.
  const root = key === 'default' ? `:root:not([data-theme]), :root[data-theme='default']` : `:root[data-theme='${key}']`;
  const scope = (suffix) =>
    root
      .split(', ')
      .map((sel) => sel + suffix)
      .join(', ');

  const base = root;
  const media = '  ' + scope(`:not([data-mode='light'])`);
  const forced = scope(`[data-mode='dark']`);

  out.push(`/* ${theme.label} — ${theme.blurb} */`);
  out.push(`${base} {`);
  out.push(vars(theme, 'light'));
  out.push('}');
  out.push('');
  out.push('@media (prefers-color-scheme: dark) {');
  out.push(`${media} {`);
  out.push(vars(theme, 'dark', '    '));
  out.push('  }');
  out.push('}');
  out.push('');
  out.push(`${forced} {`);
  out.push(vars(theme, 'dark'));
  out.push('}');
  out.push('');
}

// Swatch previews for the picker: the same variables, scoped to one element, so
// a swatch is literally a miniature of the theme rather than a hand-kept copy of
// its colours. The mode is explicit here because the picker resolves 'system'
// itself, and the swatches must agree with the preview beside them.
out.push('/* Picker swatches */');
for (const [key, theme] of Object.entries(THEMES)) {
  for (const mode of ['light', 'dark']) {
    out.push(`[data-preview='${key}'][data-preview-mode='${mode}'] {`);
    out.push(vars(theme, mode));
    out.push('}');
    out.push('');
  }
}

writeFileSync('app/themes.css', out.join('\n'));
console.log(
  `wrote app/themes.css — ${Object.keys(THEMES).length} themes, ${Object.keys(THEMES).length * 3} blocks`,
);
